def generate_training_code(best_model_name, best_params, problem_type):
    """
    Generate Python training code based on best model
    """

    code = "# Auto-generated by ModelSmith\n\n"

    # -------------------------------
    # Imports
    # -------------------------------
    code += "import pandas as pd\n"

    if best_model_name == "random_forest":
        if problem_type == "classification":
            code += "from sklearn.ensemble import RandomForestClassifier\n\n"
        else:
            code += "from sklearn.ensemble import RandomForestRegressor\n\n"

    elif best_model_name == "xgboost":
        if problem_type == "classification":
            code += "from xgboost import XGBClassifier\n\n"
        else:
            code += "from xgboost import XGBRegressor\n\n"

    elif best_model_name == "logistic_regression":
        code += "from sklearn.linear_model import LogisticRegression\n\n"

    elif best_model_name == "svm":
        if problem_type == "classification":
            code += "from sklearn.svm import SVC\n\n"
        else:
            code += "from sklearn.svm import SVR\n\n"

    elif best_model_name == "neural_network":
        code += "from tensorflow.keras.models import Sequential\n"
        code += "from tensorflow.keras.layers import Dense\n\n"

    # -------------------------------
    # Model Initialization
    # -------------------------------
    code += "# Model initialization\n"

    if best_model_name == "neural_network":
        code += "model = Sequential([\n"
        code += "    Dense(32, activation='relu'),\n"
        code += "    Dense(16, activation='relu'),\n"
        code += "    Dense(1)\n"
        code += "])\n\n"
    else:
        params_str = ", ".join([f"{k}={v}" for k, v in best_params.items()])
        code += f"model = {model_class_name(best_model_name, problem_type)}({params_str})\n\n"

    # -------------------------------
    # Training
    # -------------------------------
    code += "# Train model\n"
    code += "model.fit(X_train, y_train)\n\n"

    # -------------------------------
    # Prediction
    # -------------------------------
    code += "# Predict\n"
    code += "predictions = model.predict(X_test)\n"

    return code


def model_class_name(name, problem_type):
    mapping = {
        "random_forest": "RandomForestClassifier" if problem_type == "classification" else "RandomForestRegressor",
        "xgboost": "XGBClassifier" if problem_type == "classification" else "XGBRegressor",
        "logistic_regression": "LogisticRegression",
        "svm": "SVC" if problem_type == "classification" else "SVR"
    }
    return mapping.get(name, "")