def generate_training_code(best_model_name, best_params, problem_type):
    """
    Generate Python training code based on best model
    """

    code = "# Auto-generated by ModelSmith\n\n"

    # -------------------------------
    # Imports
    # -------------------------------
    code += "import pandas as pd\n"

    if best_model_name == "random_forest":
        if problem_type == "classification":
            code += "from sklearn.ensemble import RandomForestClassifier\n\n"
        else:
            code += "from sklearn.ensemble import RandomForestRegressor\n\n"

    elif best_model_name == "xgboost":
        if problem_type == "classification":
            code += "from xgboost import XGBClassifier\n\n"
        else:
            code += "from xgboost import XGBRegressor\n\n"

    elif best_model_name == "logistic_regression":
        code += "from sklearn.linear_model import LogisticRegression\n\n"

    elif best_model_name == "svm":
        if problem_type == "classification":
            code += "from sklearn.svm import SVC\n\n"
        else:
            code += "from sklearn.svm import SVR\n\n"

    elif best_model_name == "lightgbm":
        if problem_type == "classification":
            code += "from lightgbm import LGBMClassifier\n\n"
        else:
            code += "from lightgbm import LGBMRegressor\n\n"

    elif best_model_name == "neural_network":
        code += "from tensorflow.keras.models import Sequential\n"
        code += "from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input\n"
        code += "from tensorflow.keras.optimizers import Adam\n\n"

    # -------------------------------
    # Model Initialization
    # -------------------------------
    code += "# Model initialization\n"

    if best_model_name == "neural_network":
        dropout_rate = best_params.get('dropout_rate', 0.2)
        learning_rate = best_params.get('learning_rate', 0.001)
        epochs = best_params.get('epochs', 100)
        batch_size = best_params.get('batch_size', 32)
        final_layer = "Dense(1, activation='sigmoid')" if problem_type == "classification" else "Dense(1)"
        code += "model = Sequential([\n"
        code += "    Input(shape=(X_train.shape[1],)),\n"
        code += "    Dense(64, activation='relu'),\n"
        code += "    BatchNormalization(),\n"
        code += f"    Dropout({dropout_rate}),\n"
        code += "    Dense(32, activation='relu'),\n"
        code += "    BatchNormalization(),\n"
        code += f"    Dropout({dropout_rate}),\n"
        code += f"    {final_layer}\n"
        code += "])\n\n"
        code += f"model.compile(optimizer=Adam(learning_rate={learning_rate}), loss={'\"binary_crossentropy\"' if problem_type == 'classification' else '\"mse\"'}, metrics=[{'\"accuracy\"' if problem_type == 'classification' else '\"mae\"'}])\n\n"
        code += "# Train model\n"
        code += f"model.fit(X_train, y_train, epochs={epochs}, batch_size={batch_size})\n\n"
    else:
        params_str = ", ".join([f"{k}={v}" for k, v in best_params.items()])
        code += f"model = {model_class_name(best_model_name, problem_type)}({params_str})\n\n"
        code += "# Train model\n"
        code += "model.fit(X_train, y_train)\n\n"

    # -------------------------------
    # Prediction
    # -------------------------------
    code += "# Predict\n"
    code += "predictions = model.predict(X_test)\n"

    return code


def model_class_name(name, problem_type):
    mapping = {
        "random_forest": "RandomForestClassifier" if problem_type == "classification" else "RandomForestRegressor",
        "xgboost": "XGBClassifier" if problem_type == "classification" else "XGBRegressor",
        "logistic_regression": "LogisticRegression",
        "svm": "SVC" if problem_type == "classification" else "SVR",
        "lightgbm": "LGBMClassifier" if problem_type == "classification" else "LGBMRegressor"
    }
    return mapping.get(name, "")